### ISSUE TITLE
The rich text editor 'Codemirror' allows to execute JS code on the page

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-content#18]
**How to reproduce:**
1. Open any content item (page or template)  More -> Content  -> Pages
2. Add this line ```<img src=/ onerror=alert(1)>```  to the any content item then  click save
3, Got the browser alert popup

**Technical details:**
Need to restrict any JS code execution for the content items  in design mode.

**Comment by ilyawzrd** [comment]
**For example, we have script with Codemirror initialization:**
```
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
      mode: "application/xml",
      styleActiveLine: true,
      lineNumbers: true,
      lineWrapping: true
    });
```
 **Create an element**
   ` var el = document.createElement("html");`
    **Copy inside this element value of Codemirror area**
    `el.innerHTML = editor.getValue();`
**On focus on Codemirror area run the function that will block events only inside this area**

- var dom - array of all html elements inside Codemirror area
- var km - array of events(without "on"),it's only example,so it's just some of them

  ```
  editor.on("focus", () => {
      var dom = el.getElementsByTagName("*"); 
      var km = [
        "click",
        "error",
        "dblclick",
        "mousedown",
        "mousemove",
        "mouseover",
        "mouseout",
        "mouseup",
        "mouseenter",
        "mouseleave",
        "keydown",
        "keypress",
        "keyup"
      ];
      for (var i = 0, l = dom.length; i < l; i++) {
        for (var n = 0, c = km.length; n < c; n++) {
          dom[i]["on" + km[n]] = function(e) {
            e = e || event;
            e.preventDefault();
            return false;
          };
        }
      }
    });
```

**Comment by tatarincev** [comment]
I can't accept this solution, there  should be something another way most easiest.

**Comment by tatarincev** [comment]
@yecli  Could you take a look at this issue?

**Comment by yecli** [comment]
Yes, I'll check

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-module-core/releases/v2.25.18
