### ISSUE TITLE
Unable to rename theme when Azure blobs used

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-content#2]
500 error occurs.
How to reproduce:
1. Go to http://demovc-admin-dev.azurewebsites.net
2. Create theme with any name
3. Try to rename theme
![screenshot 360](https://user-images.githubusercontent.com/6369252/29824894-1ec16742-8cec-11e7-98ae-92b68b6ec969.png)

**Comment by tatarincev** [comment]
There need to replace rename operation to the  copy and delete  operations

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-content/releases/tag/v2.13.8
