### ISSUE TITLE
Inconsistencies when adding a blog in admin interface.

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-content#22]
Client message:
Trying to create a new blog on our Virto site in the same way as the Electronics demo site.

When I add the blog it seems to create a page rather than a blog folder and the total blogs still displays as zero (screenshots attached).

Problems:
1. Adding blog adds page instead.
2. Adding blog or post does not increase blog count

**Comment by yecli** [comment]
Problem is fixed. There is still not clear behavior with saving blog - it could overwrite the first page of existing one with the same name. Video with demo could be found in #23.

**Comment by SupportMgr** [comment]
Please let Support know when the issue is resolved and release number.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-content/v2.13.10
