### ISSUE TITLE
Fix theme upload

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-content#26]
"Theme upload" is broken in admin UI:
![image](https://user-images.githubusercontent.com/5801549/65426131-4b92bd00-de18-11e9-8595-11268b1e42c1.png)

note: .zip file was uploaded, but failed to execute "unpack".
https://github.com/VirtoCommerce/vc-platform/issues/1577

**Comment by trueboroda** [comment]
The error in the form in which it was founded is not reproduced. However, several potential hazards have been identified that need to be addressed.
- The user is not able to specify the name of the new theme that be uploaded from the archive.
- The archive is always unpacked in the path 'default' that according to the theme with such name. Moreover, if such a theme already exists, the user is not asked for confirmation. It can accidentally damage the theme files.

**Comment by eMazeika** [comment]
@trueboroda I do confirm your observations:
![image](https://user-images.githubusercontent.com/5801549/72239474-d70fa400-35e9-11ea-9cc0-65edc3466016.png)

**Comment by yecli** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-content/releases/tag/v2.13.12
